version: 0.0
os: linux

files:
  - source: /
    destination: /home

permissions:
  - object: /home
    mode: 775
    type:
      - file
      - directory

hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
